# Generated by Django 4.1.2 on 2022-10-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_blog', '0002_postbook_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='postbook',
            name='author',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='postbook',
            name='pages',
            field=models.IntegerField(null=True),
        ),
    ]
