# Generated by Django 4.1.2 on 2022-10-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_blog', '0003_postbook_author_postbook_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postbook',
            name='author',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='postbook',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
