# Generated by Django 4.1.2 on 2022-10-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_blog', '0004_alter_postbook_author_alter_postbook_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postbook',
            old_name='description',
            new_name='short_description',
        ),
        migrations.AddField(
            model_name='postbook',
            name='long_description',
            field=models.TextField(null=True),
        ),
    ]
